### ISSUE TITLE
end in function name

### ISSUE THREAD

**Issue by Rochet2** [FireZenk/language-lua#12]
Expected ident:
```lua
function Tend()
    -- code
end
```

Actual result:
```lua
function Tend()
-- code
end
```

As you can see, the code is not idented correctly inside the function.
This bug occurs when formatting or writing code normally.
I used [this](https://atom.io/packages/auto-indent), but that just uses core functionality.
The reason seems to be the `end` in the function name. Using capital `E` for example does not have the same effect.
It does not matter where the word `end` is in the function name. For example the following doesnt work: `local function SomeTable.TestTendIdent(args)`

Additionally code in other places similarily behaves incorrectly for identation.
For example code in strings: `local a = "this idents next line : do"`

- Atom version: 0.190.0
- package version: 0.1.0
- OS: windows 7

**Comment by karai17** [comment]
I don't have this issue. When I write `if whatever then` and press enter, the next line is indented. If I press enter again and type `end`, end corrects its indentation. Pressing up from there puts me at the right indentation level.

**Comment by Rochet2** [comment]
> I don't have this issue. When I write if whatever then and press enter, the next line is indented. If I press enter again and type end, end corrects its indentation. Pressing up from there puts me at the right indentation level.

Did you test with functions like I described - I stricly described this as a function issue.
__I didn't say IF statements would not work.__

Also similar problems with comments it seems

**Comment by karai17** [comment]
Oh hye, after re-reading your post and testing out your exact circumstances, it does seem to be a real bug. Sorry!

**Comment by FireZenk** [comment]
TODO:
- Test with Atom 1.x

**Comment by Rochet2** [comment]
Still happening with Atom 1.0.7, language-lua 0.9.4, auto-indent 0.5.0

**Comment by urzds** [comment]
I also have this issue with the following code (expected indention):
```lua
			local endpoint = etcd.endpoint(endpoint_url)
			endpoint:get{key}
```

It is instead indented like this:
```lua
			local endpoint = etcd.endpoint(endpoint_url)
		endpoint:get{key}
```

This also happens whenever I modify the line in any way.

It does not happen when I paste the code.
