### ISSUE TITLE
Atom not propagating 0.9.3.1

### ISSUE THREAD

**Issue by karai17** [FireZenk/language-lua#18]
It seems like Atom only recognizes 3-level version numbers so 0.9.3.1 is being ignored since there is already a 0.9.3 release. Could you bump the version to 0.9.4 so Atom will recognize it?

**Comment by shakesoda** [comment]
Are you sure that's the cause? Looks like package.json wasn't updated.

**Comment by FireZenk** [comment]
Done https://github.com/FireZenk/language-lua/releases/tag/v0.9.4
