### ISSUE TITLE
Properly highlight goto

### ISSUE THREAD

**Issue by Vexatos** [FireZenk/language-lua#21]
```lua
local i = 0
::somelabel::
print("Hello")
i = i + 1
if i < 10 then
  goto somelabel
end
```

In this example, neither the label definition nor the `goto` statement are being highlighted. It would be nice if they were. For the label definition, the colons and the label name should probably be highlighted differently.

**Comment by rm-code** [comment]
I added the goto to the list of control keywords in my own fork. No idea how the :: should be handled though:
![screenshot 2015-12-07 12 52 54](https://cloud.githubusercontent.com/assets/11627131/11626234/7df25f02-9ce1-11e5-9d61-dbfdb40dc998.png)

@Vexatos What do you think?

**Comment by Vexatos** [comment]
Looks decent to me-
