### ISSUE TITLE
v0.9.7 is not in the Atom package registry

### ISSUE THREAD

**Issue by fusion809** [FireZenk/language-lua#33]
Hi,

I've noticed that version 0.9.7 of this package has been tagged but is not present in the Atom package repository (i.e., apm install language-lua installs v0.9.4 of this package as it's the latest version of the package in the Atom package registry). Guessing you's haven't been using `apm publish patch` to publish the releases since 0.9.4? 

Thanks for your time,
Brenton

**Comment by FireZenk** [comment]
Fixed, but renamed to 0.9.11 https://atom.io/packages/language-lua

Thanks
