### ISSUE TITLE
Pico8 file support

### ISSUE THREAD

**Issue by svencharleer** [FireZenk/language-lua#36]
Not really an issue, but nice to have. Would you mind adding "p8" files to the list of supported files in the grammars/lua.cson file? There's a big community of Pico-8 (http://www.lexaloffle.com/pico-8.php) developers who I'm sure would be very grateful ;)

**Comment by tobiasvl** [comment]
https://github.com/keiyakins/language-pico8

**Comment by tobiasvl** [comment]
https://github.com/tobiasvl/language-pico8
